// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgU1JWnCB8MUZIwvYQYKkla5d3rvhSDMY',
    appId: '1:187022405544:android:f2eb70cdf6b2b09dc2b79d',
    messagingSenderId: '187022405544',
    projectId: 'sju-voting-app',
    databaseURL: 'https://sju-voting-app-default-rtdb.firebaseio.com',
    storageBucket: 'sju-voting-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaX-EIv2ZisJBMBRWAM3Sj_qXKUTKWYgE',
    appId: '1:187022405544:ios:da88603a7b6d1a8dc2b79d',
    messagingSenderId: '187022405544',
    projectId: 'sju-voting-app',
    databaseURL: 'https://sju-voting-app-default-rtdb.firebaseio.com',
    storageBucket: 'sju-voting-app.appspot.com',
    iosBundleId: 'com.example.onlineVotingApp',
  );
}
